spring.datasource.url=jdbc:h2:mem:specradar;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false

api.security.token.secret=segredo-de-teste-nao-utilizar-em-producao

api.security.allowed-origins=http://localhost:5500

specradar.ml.url=http://localhost:19999
specradar.ml.timeout-ms=300

specradar.seed.admin-login=admin@specradar.com
specradar.seed.admin-password=admin12345
specradar.seed.analista-login=analista@specradar.com
specradar.seed.analista-password=analista12345
specradar.seed.ranger-raptor-path=dados/ranger-raptor.json

logging.level.br.com.fiap.specradar=INFO
